#requires -Version 5.1
<#
.SYNOPSIS
    Installs mnemodex -- the memory index for AI coding agents.

.DESCRIPTION
    Downloads the mnemodex repository (default branch) and installs it under
    $env:LOCALAPPDATA\mnemodex, then creates a launcher script at
    $env:LOCALAPPDATA\mnemodex\bin\mnemodex.ps1.

    Usage:
        Invoke-WebRequest -UseBasicParsing https://raw.githubusercontent.com/beijixingdeyan/mnemodex/main/install.ps1 -OutFile install.ps1
        powershell -ExecutionPolicy Bypass -File install.ps1

    Requires Python 3.9 or newer. Only paths under $env:LOCALAPPDATA are
    touched. Compatible with Windows PowerShell 5.1 and PowerShell 7+.
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'  # much faster Invoke-WebRequest

# --- configuration ------------------------------------------------------------
$Repo    = 'beijixingdeyan/mnemodex'
$Branch  = 'main'
$BaseUrl = "https://github.com/$Repo"
$ZipUrl  = "$BaseUrl/archive/refs/heads/$Branch.zip"

if (-not $env:LOCALAPPDATA) {
    throw 'The LOCALAPPDATA environment variable is not set; cannot determine the install directory.'
}
$InstallDir = Join-Path $env:LOCALAPPDATA 'mnemodex'
$BinDir     = Join-Path $InstallDir 'bin'
$Launcher   = Join-Path $BinDir 'mnemodex.ps1'

# TLS 1.2 for older .NET Framework builds (no-op on PowerShell 7).
try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch { }

function Write-Info {
    param([string]$Message)
    Write-Host "mnemodex: $Message"
}

function Test-UsablePython {
    param([string]$CommandLine)
    try {
        & $CommandLine -c 'import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)' 2>$null
        return $LASTEXITCODE -eq 0
    } catch {
        return $false
    }
}

# --- 1. find a Python 3.9+ interpreter ----------------------------------------
$PythonExe = $null
foreach ($candidate in @('python', 'python3', 'py')) {
    $resolved = Get-Command $candidate -ErrorAction SilentlyContinue
    if (-not $resolved) { continue }
    $usable = if ($candidate -eq 'py') { Test-UsablePython 'py' } else { Test-UsablePython $resolved.Source }
    if ($usable) {
        $PythonExe = $resolved.Source
        break
    }
}
if (-not $PythonExe) {
    throw 'Python 3.9 or newer is required but was not found. Install Python from https://www.python.org and re-run this installer.'
}
Write-Info "Using Python: $PythonExe"

# --- 2. download and extract ---------------------------------------------------
$tempZip = Join-Path $env:TEMP "mnemodex-$Branch.zip"
Write-Info "Downloading $ZipUrl"
Invoke-WebRequest -Uri $ZipUrl -OutFile $tempZip -UseBasicParsing

Write-Info "Installing to $InstallDir"
if (Test-Path $InstallDir) { Remove-Item -Recurse -Force $InstallDir }
New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
Expand-Archive -Path $tempZip -DestinationPath $InstallDir -Force
Remove-Item -Path $tempZip -Force

# The GitHub zip wraps everything in a "mnemodex-<branch>" folder; move it up.
$inner = Get-ChildItem -Path $InstallDir -Directory | Where-Object Name -like 'mnemodex-*' | Select-Object -First 1
if ($inner) {
    Get-ChildItem -Path $inner.FullName -Force | Move-Item -Destination $InstallDir -Force
    Remove-Item -Recurse -Force $inner.FullName
}

if (-not (Test-Path (Join-Path $InstallDir 'mnemodex\__main__.py'))) {
    throw "Installation incomplete: mnemodex package not found under $InstallDir"
}

# --- 3. write the launcher ------------------------------------------------------
New-Item -ItemType Directory -Path $BinDir -Force | Out-Null
$launcherBody = @'
# Generated by the mnemodex installer - do not edit.
$env:PYTHONPATH = "__INSTALL_DIR__" + $(if ($env:PYTHONPATH) { [IO.Path]::PathSeparator + $env:PYTHONPATH } else { '' })
& "__PYTHON__" -m mnemodex @args
exit $LASTEXITCODE
'@
$launcherBody = $launcherBody.Replace('__INSTALL_DIR__', $InstallDir).Replace('__PYTHON__', $PythonExe)
Set-Content -Path $Launcher -Value $launcherBody -Encoding UTF8
Write-Info "Launcher written to $Launcher"

# --- 4. report success -----------------------------------------------------------
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
$inPath = $false
if ($userPath) { $inPath = ($userPath -split ';') -contains $BinDir }
if (-not $inPath) {
    Write-Info "Add $BinDir to your user PATH so 'mnemodex' works from any shell:"
    $snippet = "[Environment]::SetEnvironmentVariable('Path', '$BinDir;' + [Environment]::GetEnvironmentVariable('Path','User'), 'User')"
    Write-Host "    $snippet" -ForegroundColor Cyan
    Write-Host '    $env:Path = "$env:LOCALAPPDATA\mnemodex\bin;' + '$env:Path"   # current session only' -ForegroundColor Cyan
    $next = "Then run 'mnemodex init' in your repository"
} else {
    $next = "Next step: run 'mnemodex init' in your repository"
}
Write-Info "Installed mnemodex to $InstallDir"
Write-Info "$next to create the store."
Write-Info "See 'mnemodex --help' for all commands."