#!/bin/sh
# ---------------------------------------------------------------------------
# mnemodex installer -- the memory index for AI coding agents.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/beijixingdeyan/mnemodex/main/install.sh | sh
#
# Installs mnemodex into $HOME/.local/share/mnemodex (via git clone, or the
# repository tarball) and writes a launcher to $HOME/.local/bin/mnemodex.
# Needs sh, tar, and either git, curl, or wget. Only touches paths in $HOME.
# ---------------------------------------------------------------------------

# Be strict where the shell supports it (plain POSIX sh may lack pipefail).
if (set -o pipefail) 2>/dev/null; then set -euo pipefail; else set -eu; fi
: "${HOME:?The HOME environment variable must be set}"

REPO="beijixingdeyan/mnemodex"
BRANCH="main"
BASE_URL="https://github.com/${REPO}"
TARBALL_URL="${BASE_URL}/archive/refs/heads/${BRANCH}.tar.gz"
INSTALL_DIR="${HOME}/.local/share/mnemodex"
BIN_DIR="${HOME}/.local/bin"
LAUNCHER="${BIN_DIR}/mnemodex"

err() { printf 'mnemodex: ERROR: %s\n' "$*" >&2; exit 1; }
info() { printf 'mnemodex: %s\n' "$*"; }
trap 'info "Installation failed -- see the message above. Nothing outside \$HOME was changed."' ERR

# --- 1. find a Python 3.9+ interpreter ----------------------------------------
PY=""
for candidate in python3 python py; do
    if command -v "${candidate}" >/dev/null 2>&1 &&
        "${candidate}" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)' >/dev/null 2>&1; then
        PY="${candidate}"
        break
    fi
done
[ -n "${PY}" ] ||
    err "Python 3.9 or newer is required but was not found in PATH. Install Python and re-run this script."
info "Using ${PY} ($("${PY}" --version 2>&1 || true))"

# --- 2. fetch mnemodex ----------------------------------------------------------
info "Installing mnemodex (${BRANCH}) to ${INSTALL_DIR}"
mkdir -p "$(dirname "${INSTALL_DIR}")"

if [ -f "${INSTALL_DIR}/mnemodex/__main__.py" ]; then
    # Already installed: refresh in place when it is a git checkout.
    if [ -d "${INSTALL_DIR}/.git" ] && command -v git >/dev/null 2>&1; then
        info "Updating existing installation"
        git -C "${INSTALL_DIR}" pull --ff-only --quiet
    else
        info "Already installed at ${INSTALL_DIR} -- leaving it untouched."
    fi
elif command -v git >/dev/null 2>&1; then
    info "Cloning ${BASE_URL} (branch ${BRANCH})"
    git clone --depth 1 --branch "${BRANCH}" "${BASE_URL}" "${INSTALL_DIR}"
elif command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1; then
    info "Downloading ${TARBALL_URL}"
    if command -v curl >/dev/null 2>&1; then
        fetch() { curl -fsSL "$@"; }
    else
        fetch() { wget -qO- "$@"; }
    fi
    rm -rf "${INSTALL_DIR}"
    mkdir -p "${INSTALL_DIR}"
    fetch "${TARBALL_URL}" | tar -xz -C "${INSTALL_DIR}" --strip-components=1
else
    err "neither git, curl, nor wget is available. Install one of them and re-run this script."
fi
[ -f "${INSTALL_DIR}/mnemodex/__main__.py" ] ||
    err "installation incomplete: mnemodex package not found under ${INSTALL_DIR}"

# --- 3. write the launcher --------------------------------------------------------
mkdir -p "${BIN_DIR}"
cat > "${LAUNCHER}" <<EOF
#!/bin/sh
# mnemodex launcher -- generated by install.sh, do not edit.
export PYTHONPATH="${INSTALL_DIR}\${PYTHONPATH:+:\$PYTHONPATH}"
exec "${PY}" -m mnemodex "\$@"
EOF
chmod +x "${LAUNCHER}"
info "Launcher written to ${LAUNCHER}"

# --- 4. report success -------------------------------------------------------------
info "Installed mnemodex to ${INSTALL_DIR}"
if printf '%s' "${PATH}" | grep -F -q "${BIN_DIR}"; then
    info "Next step: run 'mnemodex init' in your repository to create the store."
else
    info "Add ${BIN_DIR} to your PATH, for example:"
    info '  export PATH="$HOME/.local/bin:$PATH"'
    info "Then run 'mnemodex init' in your repository to create the store."
fi
info "See 'mnemodex --help' for all commands."