"""Exporters: turn mnemodex state into shareable artifacts.

* ``export memory``        → Markdown / JSON (team memory, git-trackable)
* ``export agent``         → AGENTS.md / CLAUDE.md / CURSOR rules that make
                             Claude Code, Codex and Cursor "instantly aware"
                             of the repo before the first query
* ``export index``         → a human-readable summary of the index
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional

from . import util
from .session import Session


def export_memory(session: Session, fmt: str = "md", kind: Optional[str] = None, tag: Optional[str] = None) -> str:
    if fmt == "json":
        return util.format_json(session.memory.export_json())
    return session.memory.export_markdown(kind=kind, tag=tag)


def export_index_summary(session: Session) -> str:
    data = session.require_index()
    summary = data.get("summary", {})
    lines = [
        f"# Repository index — {data.get('root_name', '?')}",
        "",
        f"_Indexed at {util.iso_now()} · format v{data.get('format_version')}_",
        "",
        "## Summary",
        "",
        "| metric | value |",
        "| --- | --- |",
        f"| files | {summary.get('files', 0)} |",
        f"| lines | {summary.get('lines', 0):,} |",
        f"| symbols | {summary.get('symbols', 0)} |",
        f"| graph edges | {summary.get('edges', 0)} |",
        f"| duration | {summary.get('duration_ms', 0)} ms |",
        "",
        "## Languages",
        "",
    ]
    for lang, count in sorted(summary.get("languages", {}).items(), key=lambda kv: -kv[1]):
        lines.append(f"* {lang}: {count} files")
    search = session.search_index()
    lines += ["", "## Top symbols by page-rank", ""]
    graph = session.graph()
    pr = graph.page_rank(iterations=15)
    ranked = sorted(
        ((p, n) for n in graph.nodes.values() if n.kind == "symbol" for p in [pr.get(n.id, 0)]),
        key=lambda t: -t[0],
    )[:20]
    for score, node in ranked:
        lines.append(f"* `{node.attrs.get('name')}` ({node.attrs.get('kind')}) — `{node.attrs.get('path')}`")
    return "\n".join(lines)


def agent_files(session: Session) -> Dict[str, str]:
    """Generate per-agent bootstrap files as {relative_path: content}."""
    summary = session.require_index().get("summary", {})
    root = session.repo_root
    file_count = summary.get("files", 0)
    symbol_count = summary.get("symbols", 0)
    lang_bullets = "".join(
        f"* {lang}: {count} files\n" for lang, count in sorted(summary.get("languages", {}).items(), key=lambda kv: -kv[1])[:6]
    )
    common = f"""# Repository brief (generated by mnemodex)

This repository is indexed by [mnemodex](https://github.com/mnemodex/mnemodex).
{file_count} files, {symbol_count} extracted symbols.

{lang_bullets or "* no index yet"}\
When you need facts about this codebase, prefer the mnemodex tools over
guessing: `mnemodex recall <topic>` or `mnemodex ask <topic>`.

Record durable knowledge (decisions, gotchas, conventions, API notes) with:

    mnemodex add "<what you learned>" --kind gotcha --tags cache,auth

Workshop rule: if the repo has a `.mnemodex/` store, consult it before
editing code you have not touched this session.
"""
    claude = f"""# CLAUDE.md — auto-generated by mnemodex ({util.iso_now()})

{common}
## How to use mnemodex from Claude Code

* Memory store: `.mnemodex/` (created by `mnemodex init`)
* `mnemodex recall <topic>` — pull durable decisions/gotchas
* `mnemodex ask <topic>` — token-budgeted context pack
* `mnemodex add "…" --kind decision` — persist something non-obvious
* `mnemodex serve` — run the MCP server and add it as a tool source
"""
    agents_md = f"""# AGENTS.md — auto-generated by mnemodex ({util.iso_now()})

{common}
If you are an agent with shell access, `mnemodex ask <topic>` returns the
best available context for a task. If mnemodex is not installed, read
`docs/` and the symbol index yourself.
"""
    cursor_rules = f"""# .cursor/rules/mnemodex.mdc — auto-generated by mnemodex ({util.iso_now()})

---
description: Consult and maintain repository memory via mnemodex
globs: **/*.py, **/*.{'{js,ts,rs,go,java,c,cpp}'}
---

{common}"""
    return {
        "CLAUDE.md": claude,
        "AGENTS.md": agents_md,
        ".cursor/rules/mnemodex.mdc": cursor_rules,
    }


def write_agent_files(session: Session, targets: Optional[List[str]] = None, dry_run: bool = False) -> List[str]:
    """Write agent bootstrap files into the repo. Returns written paths.

    targets: subset of ['claude', 'codex', 'cursor'] — default all.
    """
    wanted = set(targets or ["claude", "codex", "cursor"])
    created: List[str] = []
    for rel, content in agent_files(session).items():
        if rel == "CLAUDE.md" and "claude" not in wanted:
            continue
        if rel == "AGENTS.md" and "codex" not in wanted:
            continue
        if rel.startswith(".cursor") and "cursor" not in wanted:
            continue
        path = os.path.join(session.repo_root, rel)
        if dry_run:
            created.append(rel + " (dry-run)")
            continue
        util.atomic_write_text(path, content)
        created.append(rel)
    return created